apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 1
  name: argocd
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "https://github.com/btwseeu78/argo-cd-by-argocd.git"
    - "https://argoproj.github.io/argo-helm"
status: {}
